# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTraining' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RxTraining
  
  pod 'RxSwift', '6.0.0'
  pod 'RxCocoa', '6.0.0'
  pod 'Alamofire'
  
end
