# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTraining' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RxTraining
  
  pod 'RxSwift', '6.0.0'
  pod 'RxCocoa', '6.0.0'
  pod 'Alamofire', '~> 4.6'
  pod 'BEMCheckBox'
  pod 'ObjectMapper'
  pod 'RxDataSources'
  pod 'Kingfisher', '~> 5.15'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'Then'
  
end
